name: PandA
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - tensorly==0.7.0
    - opencv-python==4.1.2.30
    - boto3==1.21.8
    - botocore==1.24.8
    - imageio==2.14.1
    - matplotlib==3.5.1
    - nltk==3.7
    - numpy
    - Pillow==9.0.1
    - requests==2.27.0
    - bs4
    - ipykernel
    - jupyterlab